### ISSUE TITLE
Doesnt have upper right side additional menu, like in your video

### ISSUE THREAD

**Issue by myownstandard** [GitMurf/masonry-vanilla#3]
![Снимок экрана 2021-02-15 в 13 48 421](https://user-images.githubusercontent.com/78643199/107937608-37afa400-6f95-11eb-8753-934fa5449165.jpg)

**Comment by GitMurf** [comment]
@myownstandard did you add the roam/js for those scripts shown later on in the readme? The buttons come from the additional optional javascript.

https://github.com/GitMurf/masonry-vanilla#optional-roamjs-scripts

**Comment by GitMurf** [comment]
Closing this out as no response.
